//! Generation of the memory map (Map of Content / `_MOC.md`) for a single project.
//!
//! The map is grouped by category (`type`), listing wikilinks to every
//! memory along with its description, followed by a "Relations" section that
//! summarizes links between memories (the `links` field). The Obsidian Graph
//! View will automatically display these connections.

use crate::cluster;
use crate::config::{ensure_dir, Config};
use crate::links;
use crate::memory::{load_all, now_rfc3339, Memory};
use crate::similarity;
use std::collections::BTreeMap;

/// Number of smart relation suggestions shown per memory in the map.
const MOC_SUGGEST_TOP: usize = 3;
/// Score threshold for a suggestion to be relevant enough to appear in the map
/// (stricter than the tool default to keep the map uncluttered).
const MOC_SUGGEST_THRESHOLD: f64 = 0.1;

/// Build the text content of `_MOC.md` for a project.
pub fn build_moc_string(project: &str, memories: &[Memory]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# 🗺️ Memory Map — `{project}`\n\n"));
    out.push_str(&format!(
        "> Automatically generated by mcp-obsidian at {}. \
         Do not edit manually — changes will be overwritten.\n\n",
        now_rfc3339()
    ));

    if memories.is_empty() {
        out.push_str("_No memories for this project yet._\n");
        return out;
    }

    out.push_str(&format!("Total memories: **{}**\n\n", memories.len()));

    // Group by category (type).
    let mut by_kind: BTreeMap<String, Vec<&Memory>> = BTreeMap::new();
    for m in memories {
        by_kind.entry(m.front.kind.clone()).or_default().push(m);
    }

    for (kind, items) in &by_kind {
        out.push_str(&format!("## {}\n\n", title_case(kind)));
        for m in items {
            let f = &m.front;
            let tags = if f.tags.is_empty() {
                String::new()
            } else {
                let t: Vec<String> = f.tags.iter().map(|t| format!("#{t}")).collect();
                format!("  _{}_", t.join(" "))
            };
            out.push_str(&format!("- [[{}]] — {}{}\n", f.name, f.description, tags));
        }
        out.push('\n');
    }

    // Explicit relations section (the `links` field).
    // Link graph: combines the `links` field + [[wikilink]] entries in the body.
    let graph = links::LinkGraph::build(memories);

    // Outgoing relations — only those pointing to existing memories.
    let mut has_relations = false;
    let mut relation_block = String::from("## 🔗 Relations\n\n");
    for (name, outs) in &graph.forward {
        let valid: Vec<String> = outs
            .iter()
            .filter(|t| graph.existing.contains(*t))
            .map(|t| format!("[[{t}]]"))
            .collect();
        if !valid.is_empty() {
            has_relations = true;
            relation_block.push_str(&format!("- [[{name}]] → {}\n", valid.join(", ")));
        }
    }
    if has_relations {
        out.push_str(&relation_block);
        out.push('\n');
    }

    // Backlinks (derived) — who links to whom, computed from the graph.
    if !graph.backward.is_empty() {
        out.push_str("## ⬅️ Backlinks\n\n");
        for (name, sources) in &graph.backward {
            let rendered: Vec<String> = sources.iter().map(|s| format!("[[{s}]]")).collect();
            out.push_str(&format!("- [[{name}]] ← {}\n", rendered.join(", ")));
        }
        out.push('\n');
    }

    // Tag index.
    let mut by_tag: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for m in memories {
        for tag in &m.front.tags {
            by_tag
                .entry(tag.clone())
                .or_default()
                .push(m.front.name.clone());
        }
    }
    if !by_tag.is_empty() {
        out.push_str("## 🏷️ Tag Index\n\n");
        for (tag, names) in &by_tag {
            let rendered: Vec<String> = names.iter().map(|n| format!("[[{n}]]")).collect();
            out.push_str(&format!("- **#{tag}**: {}\n", rendered.join(", ")));
        }
        out.push('\n');
    }

    // Smart relations: suggested links based on tag + content similarity (TF-IDF),
    // beyond those already linked manually. These are mere suggestions, not real links.
    let suggestions = similarity::suggest_all(memories, MOC_SUGGEST_TOP, MOC_SUGGEST_THRESHOLD);
    if !suggestions.is_empty() {
        out.push_str("## 💡 Suggested Relations\n\n");
        out.push_str(
            "> Automatic suggestions based on similarity; run `memory_suggest` \
             with `apply: true` to turn them into links.\n\n",
        );
        for (name, sugg) in &suggestions {
            let rendered: Vec<String> = sugg
                .iter()
                .map(|s| format!("[[{}]] ({:.2})", s.name, s.score))
                .collect();
            out.push_str(&format!("- [[{name}]] ⇢ {}\n", rendered.join(", ")));
        }
        out.push('\n');
    }

    // Themes: community clusters (Louvain) over the link graph. Only shown when
    // there is more than one meaningful theme (>1 cluster, at least one with >1 member).
    let clustering = cluster::cluster(memories);
    let meaningful = clustering
        .clusters
        .iter()
        .filter(|c| c.members.len() > 1)
        .count();
    if clustering.clusters.len() > 1 && meaningful >= 1 {
        out.push_str(&format!(
            "## 🧩 Themes (modularity {:.2})\n\n",
            clustering.modularity
        ));
        for (i, c) in clustering.clusters.iter().enumerate() {
            let rendered: Vec<String> = c.members.iter().map(|m| format!("[[{m}]]")).collect();
            out.push_str(&format!("- **Theme {}**: {}\n", i + 1, rendered.join(", ")));
        }
        out.push('\n');
    }

    out
}

/// Regenerate `_MOC.md` on disk for a project.
/// Returns the text content of the newly written map.
pub fn regenerate_moc(config: &Config, project: &str) -> anyhow::Result<String> {
    let memories = load_all(config, project);
    let content = build_moc_string(project, &memories);
    ensure_dir(&config.project_dir(project))?;
    std::fs::write(config.moc_file(project), &content)?;
    Ok(content)
}

fn title_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}
